import { ReaderPreset } from './types'
import { DEFAULT_READER_SETTINGS } from './defaults'

export const READER_PRESETS: ReaderPreset[] = [
    {
        id: 'default',
        name: 'Default',
        tagline: 'Balanced & Interactive',
        description: 'Standard multi-column layout with table of contents, author profile, and sidebar widgets.',
        badge: 'Recommended',
        settings: {
            ...DEFAULT_READER_SETTINGS,
            layout: {
                ...DEFAULT_READER_SETTINGS.layout,
                showNavbar: true,
                showLeftSidebar: true,
                showRightSidebar: true,
                contentWidth: 'default',
                bannerWidth: 'contained',
                titleWidth: 'contained',
                bannerMarginTop: 24,
                bannerMarginBottom: 32,
                headerAlignment: 'left',
                headerOrder: ['topbar', 'banner', 'author', 'title', 'tags'],
            },
            typography: {
                ...DEFAULT_READER_SETTINGS.typography,
                titleUppercase: false,
            },
        },
    },
    {
        id: 'awwwards',
        name: 'Awwwards Editorial',
        tagline: 'Award-Winning Magazine',
        description: 'Awwwards blog aesthetic featuring centered title & metadata, giant title scale, uppercase transform, Inter Tight 300 light prose, and breakout hero banner.',
        badge: 'Awwwards',
        settings: {
            layout: {
                showNavbar: true,
                showLeftSidebar: false,
                showRightSidebar: false,
                contentWidth: 'narrow',
                bannerWidth: 'awwwards-80',
                titleWidth: 'awwwards-80',
                bannerMarginTop: 36,
                bannerMarginBottom: 48,
                headerAlignment: 'center',
                headerOrder: ['topbar', 'title', 'author', 'banner', 'tags'],
                headerVisibility: {
                    topbar: true,
                    banner: true,
                    author: true,
                    title: true,
                    tags: true,
                },
                rightWidgets: {
                    profile: false,
                    series: false,
                    subscribeForm: false,
                    socials: false,
                },
            },
            typography: {
                headingFont: 'inter-tight',
                bodyFont: 'inter-tight',
                codeFont: 'mono',
                bodyFontSize: 17.5,
                bodyFontWeight: 300,
                headingFontWeight: 400,
                titleFontWeight: 800,
                titleScale: 1.65,
                titleUppercase: true,
                lineHeight: 1.85,
                paragraphSpacing: 28,
                headingMarginTop: 48,
                headingMarginBottom: 16,
                letterSpacing: -0.015,
                headingScale: 1.15,
            },
            appearance: {
                showReadingProgress: true,
                showTableOfContents: false,
                showShareButtons: true,
                showReadingTime: true,
                showPublishedDate: true,
                showCategory: true,
            },
        },
    },
    {
        id: 'minimal',
        name: 'Minimal',
        tagline: 'Clean & Lightweight',
        description: 'Stripped-down layout focusing purely on title, author, and prose without sidebar distractions.',
        badge: 'Clean',
        settings: {
            layout: {
                showNavbar: true,
                showLeftSidebar: false,
                showRightSidebar: false,
                contentWidth: 'default',
                bannerWidth: 'contained',
                titleWidth: 'contained',
                bannerMarginTop: 20,
                bannerMarginBottom: 28,
                headerAlignment: 'left',
                headerOrder: ['title', 'author', 'tags', 'banner', 'topbar'],
                headerVisibility: {
                    topbar: false,
                    banner: false,
                    author: true,
                    title: true,
                    tags: true,
                },
                rightWidgets: {
                    profile: false,
                    series: false,
                    subscribeForm: false,
                    socials: false,
                },
            },
            typography: {
                headingFont: 'sans',
                bodyFont: 'sans',
                codeFont: 'mono',
                bodyFontSize: 17,
                bodyFontWeight: 400,
                headingFontWeight: 700,
                titleFontWeight: 700,
                titleScale: 1.0,
                titleUppercase: false,
                lineHeight: 1.85,
                paragraphSpacing: 24,
                headingMarginTop: 32,
                headingMarginBottom: 12,
                letterSpacing: 0,
                headingScale: 1.0,
            },
            appearance: {
                showReadingProgress: true,
                showTableOfContents: false,
                showShareButtons: true,
                showReadingTime: true,
                showPublishedDate: true,
                showCategory: true,
            },
        },
    },
    {
        id: 'magazine',
        name: 'Magazine',
        tagline: 'Editorial & Storytelling',
        description: 'Visual-first presentation with prominent hero banner, serif body typography, and rich widgets.',
        badge: 'Editorial',
        settings: {
            layout: {
                showNavbar: true,
                showLeftSidebar: false,
                showRightSidebar: true,
                contentWidth: 'default',
                bannerWidth: 'breakout',
                titleWidth: 'breakout',
                bannerMarginTop: 28,
                bannerMarginBottom: 40,
                headerAlignment: 'left',
                headerOrder: ['banner', 'topbar', 'title', 'author', 'tags'],
                headerVisibility: {
                    topbar: true,
                    banner: true,
                    author: true,
                    title: true,
                    tags: true,
                },
                rightWidgets: {
                    profile: true,
                    series: true,
                    subscribeForm: true,
                    socials: true,
                },
            },
            typography: {
                headingFont: 'serif',
                bodyFont: 'serif',
                codeFont: 'mono',
                bodyFontSize: 17.5,
                bodyFontWeight: 400,
                headingFontWeight: 700,
                titleFontWeight: 800,
                titleScale: 1.2,
                titleUppercase: false,
                lineHeight: 1.9,
                paragraphSpacing: 26,
                headingMarginTop: 36,
                headingMarginBottom: 14,
                letterSpacing: 0.01,
                headingScale: 1.05,
            },
            appearance: {
                showReadingProgress: true,
                showTableOfContents: false,
                showShareButtons: true,
                showReadingTime: true,
                showPublishedDate: true,
                showCategory: true,
            },
        },
    },
    {
        id: 'developer',
        name: 'Developer',
        tagline: 'Technical & Code-Oriented',
        description: 'Optimized for technical articles with full TOC minimap, monospace accents, and expanded reading canvas.',
        badge: 'Code Focus',
        settings: {
            layout: {
                showNavbar: true,
                showLeftSidebar: true,
                showRightSidebar: true,
                contentWidth: 'wide',
                bannerWidth: 'contained',
                titleWidth: 'contained',
                bannerMarginTop: 20,
                bannerMarginBottom: 28,
                headerAlignment: 'left',
                headerOrder: ['topbar', 'title', 'tags', 'banner', 'author'],
                headerVisibility: {
                    topbar: true,
                    banner: true,
                    author: true,
                    title: true,
                    tags: true,
                },
                rightWidgets: {
                    profile: true,
                    series: true,
                    subscribeForm: false,
                    socials: true,
                },
            },
            typography: {
                headingFont: 'space-mono',
                bodyFont: 'sans',
                codeFont: 'mono',
                bodyFontSize: 16,
                bodyFontWeight: 400,
                headingFontWeight: 700,
                titleFontWeight: 700,
                titleScale: 1.0,
                titleUppercase: false,
                lineHeight: 1.75,
                paragraphSpacing: 20,
                headingMarginTop: 28,
                headingMarginBottom: 10,
                letterSpacing: -0.01,
                headingScale: 0.95,
            },
            appearance: {
                showReadingProgress: true,
                showTableOfContents: true,
                showShareButtons: true,
                showReadingTime: true,
                showPublishedDate: true,
                showCategory: true,
            },
        },
    },
    {
        id: 'distraction-free',
        name: 'Distraction Free',
        tagline: 'Pure Focus Mode',
        description: 'Immersive reading environment hiding top navbar, sidebars, and peripheral clutter.',
        badge: 'Focus',
        settings: {
            layout: {
                showNavbar: false,
                showLeftSidebar: false,
                showRightSidebar: false,
                contentWidth: 'narrow',
                bannerWidth: 'contained',
                titleWidth: 'contained',
                bannerMarginTop: 24,
                bannerMarginBottom: 32,
                headerAlignment: 'center',
                headerOrder: ['title', 'topbar', 'author', 'tags', 'banner'],
                headerVisibility: {
                    topbar: true,
                    banner: false,
                    author: true,
                    title: true,
                    tags: false,
                },
                rightWidgets: {
                    profile: false,
                    series: false,
                    subscribeForm: false,
                    socials: false,
                },
            },
            typography: {
                headingFont: 'serif',
                bodyFont: 'sans',
                codeFont: 'mono',
                bodyFontSize: 18,
                bodyFontWeight: 300,
                headingFontWeight: 600,
                titleFontWeight: 700,
                titleScale: 1.1,
                titleUppercase: false,
                lineHeight: 1.95,
                paragraphSpacing: 28,
                headingMarginTop: 36,
                headingMarginBottom: 14,
                letterSpacing: 0,
                headingScale: 1.0,
            },
            appearance: {
                showReadingProgress: true,
                showTableOfContents: false,
                showShareButtons: false,
                showReadingTime: true,
                showPublishedDate: false,
                showCategory: true,
            },
        },
    },
]
